                                        Installing Numpy Library

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


                                        Numpy Basic Array Manipulations

In [2]:
import numpy as np

                                   Multidimenional array objects (nd array)

In [3]:
# An array containing zeros

np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [4]:
# An array containing ones

np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [5]:
# A random array ( not always zeros, can be any number)

np.empty((2,2))

array([[1., 1.],
       [1., 1.]])

In [6]:
# Converting a python list into a numpy array

a=["Ali",5,34,2]
b=np.array(a)
print(b)

""" Now checking type"""

type(b)



['Ali' '5' '34' '2']


numpy.ndarray

In [7]:
# Creating an array in a given range (similar to python k loop ki range)

"""1st argument is the starting point, 2nd arg is ending point & 3rd arg is the num of steps """

np.arange(1,100,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [8]:
# Gives the shape of an array (size of array along each dimemsion)

x=np.ones((10,10))
x.shape

(10, 10)

In [9]:
# Changes the dimesnsion into n-dimension where n is the number of dimension you want

"""The size or dimension should remain same , For Eg: In x, the shape was 10x10 which is equal to 100.
    If you reshape x, the product after reshape should be 100 or it won't work"""

x=np.ones((10,10))
x.reshape((2,2,5,5))


array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]])

In [10]:
# Checking data type

y=np.empty((2,2))
y
y.dtype

dtype('float64')

In [11]:
# Gives the dimension

x=np.empty((2,5,4))
print(x)

"""The dimension of x is"""

x.ndim

[[[1.19419859e-311 1.19419618e-311 1.27276404e+232 1.14448054e+243]
  [4.45547991e+252 2.31633990e-152 1.21697543e-152 3.17247824e+180]
  [2.90892112e-014 7.20191272e+159 2.58636056e+161 2.19527311e-152]
  [1.69337237e-152 1.06098609e-153 7.35419734e+223 7.50187034e+247]
  [1.27734650e-152 1.72977319e+156 7.71463020e+199 6.99405059e-009]]

 [[1.10982361e+171 3.48989969e-086 1.05774136e-153 7.18988929e+140]
  [1.03063392e-113 7.27135128e-043 8.24227377e-072 5.40223320e-062]
  [2.25563599e-153 2.86643569e+161 1.05089607e-153 4.55071999e+198]
  [1.18125339e-076 1.05089597e-153 1.95600843e-109 1.35717430e+131]
  [6.01347002e-154 3.84568617e-086 2.31738989e-052 2.52822123e-052]]]


3

                                      
                                      Arithmetic Operation with nd arrays 

In [12]:
# Creating a random array
a=np.random.randn(10)
a


array([ 0.83184635,  0.10785245,  0.86197029,  0.61401464, -0.06247483,
        2.4813388 , -1.17423403, -0.51788369, -1.32868587, -0.90499644])

In [13]:
b=np.random.randn(10)
b

array([-1.12859568, -2.93554965,  2.08402768, -0.32141558, -0.26348386,
       -0.08031245, -0.43112405,  0.31401596, -0.80769561,  1.62762448])

In [14]:
"""All the operations are index to index"""


# Adding two arrays

a+b

array([-0.29674933, -2.8276972 ,  2.94599797,  0.29259906, -0.32595869,
        2.40102635, -1.60535808, -0.20386773, -2.13638147,  0.72262804])

In [15]:
# Sbbtracting them

a-b

array([ 1.96044203,  3.0434021 , -1.22205739,  0.93543023,  0.20100903,
        2.56165124, -0.74310998, -0.83189965, -0.52099026, -2.53262091])

In [16]:
# Multiplying them

a*b


array([-0.9388182 , -0.31660622,  1.79636994, -0.19735387,  0.01646111,
       -0.1992824 ,  0.50624053, -0.16262374,  1.07317374, -1.47299435])

In [17]:
# dividing them
a/b

array([ -0.7370632 ,  -0.03674012,   0.41360789,  -1.91034499,
         0.23711065, -30.89606674,   2.72365697,  -1.64922729,
         1.64503292,  -0.55602287])

In [18]:
# Comparison of arrays

a==b

array([False, False, False, False, False, False, False, False, False,
       False])

In [19]:
# Checking if thethe array is greater than zero

"""It will return the answer of each index in array in boolean form"""

a>0



array([ True,  True,  True,  True, False,  True, False, False, False,
       False])

In [20]:
# fetching the values greater than zero

"""We pass the whole statement as an index in the same array"""

a[a>0]


array([0.83184635, 0.10785245, 0.86197029, 0.61401464, 2.4813388 ])

                                               Indexing

In [21]:
# positive index

x=np.array([1,2,3,4,5])
x

""" The indexing is same as that of simple python list. The only difference 
    is that the indices here are of a numpy array and not of a list """


x[1]


2

In [22]:
# negative index

x[-2]

4

In [23]:
# Boolean indexing

""" This is to extract out elements by giving conditions in index """

x[x>2]

array([3, 4, 5])

In [24]:
# Fancy indexing

"""We passed a list as an index. Each index in this list gives the output that 
    corresponds to the value of that index in the original array"""

x[[2,3,4]]

array([3, 4, 5])

                                                    Slicing

In [25]:
# Making a random array of order 5x5 for slicing

a=np.random.randn(5,5)
a

array([[-0.66970714, -0.52832905,  0.32476438, -0.88512576,  0.9875199 ],
       [ 0.0731222 , -0.17189528,  1.01323033, -0.27190618,  0.68662395],
       [-0.6263941 , -0.428474  ,  0.76287729,  0.3804363 ,  0.27598567],
       [-0.72455347,  0.14688114, -0.90776396,  0.01344175, -1.92117596],
       [ 2.02950599,  0.69255954, -0.4136474 ,  0.0031128 , -0.79430052]])

In [26]:
# Slicing of rows

"""The slicing is same as of normal python string or list.
    It is slicing of rows if we consider this array as a matrix."""

""" This gives first row"""
    
a[0]

array([-0.66970714, -0.52832905,  0.32476438, -0.88512576,  0.9875199 ])

In [27]:
# slicing of coloumns

""" This gives values from coloumn 2 to coloumn 5"""

a[::,1:4] 


array([[-0.52832905,  0.32476438, -0.88512576],
       [-0.17189528,  1.01323033, -0.27190618],
       [-0.428474  ,  0.76287729,  0.3804363 ],
       [ 0.14688114, -0.90776396,  0.01344175],
       [ 0.69255954, -0.4136474 ,  0.0031128 ]])

In [28]:
# SLicing of single coloumn w.r.t it's row

'''This gives value of 5th coloumn in 1st row'''

a[0][4]   


0.9875199036333739

In [29]:
# Creating a square with ones as borders and zeros as center

s=np.ones((5,5))

print("Original matrix:")
print()
print(s)

"""The first slicing represents rows whereas slicing after comma represents coloumns"""

s[1:4,1:4]=0
s


Original matrix:

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
# Creating a chess board

"""This is done in 2 steps. In step 1 the odd rows and coloumns were made 0 using steps.
    In step 2, the even rows and coloumns were made 0 using steps"""

w=np.ones((8,8))
w

""" Step 1 """
w[0:9:2,0:9:2]=0
chessBoard=w

""" Step 2 """

chessBoard[1:9:2,1:9:2]=0
print(chessBoard)



[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


                                        Element-wise Array Functions

In [31]:
x=np.array([1,2,4,6,44])
x

array([ 1,  2,  4,  6, 44])

In [32]:
# Gives exponent

""" All the functions gives element-wise results """

np.power(x,3) # Gives cube of each element in array

array([    1,     8,    64,   216, 85184], dtype=int32)

In [33]:
# Getting square root

np.sqrt(x)

array([1.        , 1.41421356, 2.        , 2.44948974, 6.63324958])

In [34]:
# Gives square

np.square(x)

array([   1,    4,   16,   36, 1936], dtype=int32)

In [35]:
# Gives sine angle of each element

np.sin(x)

array([ 0.84147098,  0.90929743, -0.7568025 , -0.2794155 ,  0.01770193])

In [36]:
# Gives cosine angle of each element

np.cos(x)

array([ 0.54030231, -0.41614684, -0.65364362,  0.96017029,  0.99984331])

In [37]:
# Gives tangent angle of each element

np.tan(x)


array([ 1.55740772, -2.18503986,  1.15782128, -0.29100619,  0.0177047 ])

                                        Where Function

In [38]:
""" The format of where function goes like this,
    where(condition,action(if True),action otherwise) """

# It kind of works like an if condition where the condition is 1st argument with automatic if
# and 2nd argument is the fulfilment of the condition if true and 3rd argument is the else part.

salary=np.array([0,-1,50000,44000])
np.where(salary<=0,"Not Ok","Ok")

array(['Not Ok', 'Not Ok', 'Ok', 'Ok'], dtype='<U6')

                                    Mathematical & Statistical Functions

In [39]:
# Getting mean

i=np.array([1,82,3,6])
np.mean(i)

23.0

In [40]:
# Gives commulative sum

"""" Each element afterwards is equal to the sum of its previous elements """

np.cumsum(i)

array([ 1, 83, 86, 92], dtype=int32)

In [41]:
# Gives commulative product

"""" Each element afterwards is equal to the product of its previous elements """

np.cumprod(i)

array([   1,   82,  246, 1476], dtype=int32)

In [42]:
# Checking condition for each index

x=i>6
x


array([False,  True, False, False])

In [43]:
# Gives sum of all elements

np.sum(i)

92

In [44]:
# Checks if any element is True

np.any(x)

True

In [45]:
# Checks if all element are True

np.all(x)

False

In [46]:
# Sorts the array

np.sort(i)

array([ 1,  3,  6, 82])

In [47]:
# Gives unique elements

np.unique(i)

array([ 1,  3,  6, 82])

                                                File Input Output

In [48]:
# Saving an array in a file

arr1=[1,2,3,4]
arr2=[2,3,6,8,9]
arr3=[3,4,66,2,1]
np.save("singleSave.npy",arr2)

In [49]:
# loading a saved file

"""This gives the result in a dictionary. All the arrays are stored as keys and 
    can be fetched in the same manner as a key of dictionary is fetched """

np.load("singleSave.npy")

#    Since, it's a single key (array) here, therefore, the result is given directly. It 
#    would have been fetched by a dictionary key fetching method otherwise !

array([2, 3, 6, 8, 9])

In [50]:
# saving multiple arrays in a single file 

np.savez("MultiSave",arr1,arr2,arr3)
myDict=np.load("MultiSave.npz")
print(myDict)


                                            Linear Algebra Functions

In [51]:
x=np.random.randn(3,3)
y=np.random.randn(3,3)
print("x=","\n",x)
print("y=","\n",y)

x= 
 [[-0.19925803 -0.43384444  1.34521363]
 [ 1.14542225 -0.72850644 -1.35022054]
 [-0.18554395 -0.51620002 -0.16641152]]
y= 
 [[ 1.51300859 -0.53703275  1.82563984]
 [ 0.70288797 -1.1589389  -0.34444559]
 [-0.28391285 -0.8868553  -0.47505534]]


In [52]:
# Dot product of 2 matrices

np.dot(x,y)

array([[-0.98834658, -0.58320254, -0.85338851],
       [ 1.60432025,  1.42661544,  2.9834888 ],
       [-0.596314  ,  0.8454704 , -0.08187893]])

In [53]:
# Transpose of a matrix

np.transpose(x)

array([[-0.19925803,  1.14542225, -0.18554395],
       [-0.43384444, -0.72850644, -0.51620002],
       [ 1.34521363, -1.35022054, -0.16641152]])

In [54]:
# Trace of a matrix

np.trace(x)

-1.094175994510488

In [55]:
# diagonal of a matrix

np.diag(x)

array([-0.19925803, -0.72850644, -0.16641152])

In [56]:
# Eigen values and correseponding vectors of  matrix

from numpy import linalg as LA
values,vectors=LA.eig(x)
print("Eigen values are:","\n",values)
print()
print("Eigen vectors are:","\n",vectors)

Eigen values are: 
 [ 0.14743877+0.85846457j  0.14743877-0.85846457j -1.38905354+0.j        ]

Eigen vectors are: 
 [[ 0.74334274+0.j          0.74334274-0.j         -0.08873812+0.j        ]
 [ 0.09260394-0.5490341j   0.09260394+0.5490341j   0.92237665+0.j        ]
 [ 0.22144457+0.29730446j  0.22144457-0.29730446j  0.37596125+0.j        ]]


In [57]:
# Gives inverse of a matrix

LA.inv(x)

array([[ 0.54631938,  0.72740738, -1.48573919],
       [-0.41858567, -0.26830056, -1.20678076],
       [ 0.68930127,  0.02121675, -0.6092717 ]])

In [58]:
# Gives rank of  a matrix

LA.matrix_rank(x)

3

In [59]:
# Gives determinant of a matrix

LA.det(x)

-1.0538743846788503

In [60]:
# Gives adjoint of a matrix

np.matrix.getH(x)

array([[-0.19925803,  1.14542225, -0.18554395],
       [-0.43384444, -0.72850644, -0.51620002],
       [ 1.34521363, -1.35022054, -0.16641152]])

In [61]:
# Gives conjugate of a matrix

np.conjugate(x)

array([[-0.19925803, -0.43384444,  1.34521363],
       [ 1.14542225, -0.72850644, -1.35022054],
       [-0.18554395, -0.51620002, -0.16641152]])

                                                Pseudo Random Numbers

In [62]:
# To initialize

np.random.seed(7)

In [63]:
# Normal distributuion

np.random.normal(size=(3,3))

array([[ 1.69052570e+00, -4.65937371e-01,  3.28201637e-02],
       [ 4.07516283e-01, -7.88923029e-01,  2.06557291e-03],
       [-8.90385858e-04, -1.75472431e+00,  1.01765801e+00]])

In [64]:
# Uniform distributuion

np.random.uniform(size=(3,3))

array([[0.38094113, 0.06593635, 0.2881456 ],
       [0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892]])

In [65]:
# Chi Square distributuion

np.random.chisquare((5,5))

array([6.35244905, 5.19258072])

In [66]:
# Gamma distributuion

np.random.gamma((1,1))

array([0.14291176, 0.74110411])

                                     Numpy Advanced Array Manipulations

                                            Reshape Function

In [72]:
# Reshape basically changes the order of elements in matrix by manipulating axes and dimensions.
# The count of elements and elements themselves remains same. It is simply change of way a matrix 
# is written by manipulation of dimensions.

a=np.random.randn(4,5)
print("a:","\n",a)

"""The product of dimenssions should be equal when reshaping"""

a.reshape(2,2,5)

a: 
 [[-0.17953522  1.9086429   0.23986947 -1.06344985 -0.21228429]
 [ 0.92569535 -1.7279359   1.53067224 -0.23343633  0.29719528]
 [ 0.99286434 -0.93597859 -0.95960851 -0.19904275 -0.61285757]
 [-1.25337305 -0.3222009   2.71396693  1.62985742  1.13361691]]


array([[[-0.17953522,  1.9086429 ,  0.23986947, -1.06344985,
         -0.21228429],
        [ 0.92569535, -1.7279359 ,  1.53067224, -0.23343633,
          0.29719528]],

       [[ 0.99286434, -0.93597859, -0.95960851, -0.19904275,
         -0.61285757],
        [-1.25337305, -0.3222009 ,  2.71396693,  1.62985742,
          1.13361691]]])

In [79]:
# Coloumn major order or Fortran Order

a.reshape((2,2,5),order="F")

array([[[-0.17953522,  1.9086429 ,  0.23986947, -1.06344985,
         -0.21228429],
        [ 0.99286434, -0.93597859, -0.95960851, -0.19904275,
         -0.61285757]],

       [[ 0.92569535, -1.7279359 ,  1.53067224, -0.23343633,
          0.29719528],
        [-1.25337305, -0.3222009 ,  2.71396693,  1.62985742,
          1.13361691]]])

In [78]:
# Row major order or C Order


a.reshape((2,2,5),order="C")

array([[[-0.17953522,  1.9086429 ,  0.23986947, -1.06344985,
         -0.21228429],
        [ 0.92569535, -1.7279359 ,  1.53067224, -0.23343633,
          0.29719528]],

       [[ 0.99286434, -0.93597859, -0.95960851, -0.19904275,
         -0.61285757],
        [-1.25337305, -0.3222009 ,  2.71396693,  1.62985742,
          1.13361691]]])

In [82]:
# Converting in 1 dimension

x=a.ravel()
print(x)
print()
y=a.flatten()
print(y)

[-0.17953522  1.9086429   0.23986947 -1.06344985 -0.21228429  0.92569535
 -1.7279359   1.53067224 -0.23343633  0.29719528  0.99286434 -0.93597859
 -0.95960851 -0.19904275 -0.61285757 -1.25337305 -0.3222009   2.71396693
  1.62985742  1.13361691]

[-0.17953522  1.9086429   0.23986947 -1.06344985 -0.21228429  0.92569535
 -1.7279359   1.53067224 -0.23343633  0.29719528  0.99286434 -0.93597859
 -0.95960851 -0.19904275 -0.61285757 -1.25337305 -0.3222009   2.71396693
  1.62985742  1.13361691]


In [86]:
""" -1 leaves it upto numpy to complete the rest of the dimension """

a.reshape(10,-1)

array([[-0.17953522,  1.9086429 ],
       [ 0.23986947, -1.06344985],
       [-0.21228429,  0.92569535],
       [-1.7279359 ,  1.53067224],
       [-0.23343633,  0.29719528],
       [ 0.99286434, -0.93597859],
       [-0.95960851, -0.19904275],
       [-0.61285757, -1.25337305],
       [-0.3222009 ,  2.71396693],
       [ 1.62985742,  1.13361691]])

                                             Concatenate Function

In [91]:
# Row-wise concatenation

x=np.array(([1,2,3],[2,4,6]))
y=np.array(([11,12,13],[12,14,16]))

""" It requires an axis. It can either be 0 or 1. 0 represents row-wise concatenation.The number 
    of  rows increases whereas the number of coloumns remains same in row-wise concatenation """

np.concatenate((x,y),axis=0)

array([[ 1,  2,  3],
       [ 2,  4,  6],
       [11, 12, 13],
       [12, 14, 16]])

In [92]:
# Coloumn-wise concatenation

x=np.array(([1,2,3],[2,4,6]))
y=np.array(([11,12,13],[12,14,16]))

""" It requires an axis. It can either be 0 or 1. 1 represents coloumn-wise concatenation.The number 
    of  coloumns increases whereas the number of rows remains same in coloumn-wise concatenation """

np.concatenate((x,y),axis=1)

array([[ 1,  2,  3, 11, 12, 13],
       [ 2,  4,  6, 12, 14, 16]])

In [98]:
# Default Row-wise concatenation

np.vstack((x,y))

array([[ 1,  2,  3],
       [ 2,  4,  6],
       [11, 12, 13],
       [12, 14, 16]])

In [97]:
# Default Coloumn-wise concatenation

np.hstack((x,y))

array([[ 1,  2,  3, 11, 12, 13],
       [ 2,  4,  6, 12, 14, 16]])

                                               Split Function

In [121]:
# Splitting of an array into n arrays

x=np.array(([1,2,3,2,4,6,6,9,0,5,3]))

""" The first argument is of the array to be split and second is for the positions on which split occurs"""

np.split(x,[2,5,7])

[array([1, 2]), array([3, 2, 4]), array([6, 6]), array([9, 0, 5, 3])]

In [120]:
# Coloumn-wise split

x=np.array(([1,2,3,5,7,9,3],
            [2,4,6,8,10,12,14]))

""" It is a coloumn-wise split. First split of both arrays in the tuple occurs at 
    coloumn 2 and second split occurs at coloumn 5 for both arrays in the tuple. 
    The remaining elements of a single array is splitted in an array for each 
    individual array in the tuple """

np.split(x,[2,5],axis=1)

[array([[1, 2],
        [2, 4]]), array([[ 3,  5,  7],
        [ 6,  8, 10]]), array([[ 9,  3],
        [12, 14]])]

In [124]:
# Row-wise split

x=np.array(([1,2,3,5,7,9,3],
            [2,4,6,8,10,12,14]))

""" It is a row-wise split. First split of both arrays in the tuple occurs at row 2
    and second split occurs at row 5 for both arrays in the tuple. The remaining 
    elements of every array is splitted in individual arrays for each initial array"""

np.split(x,[2,5],axis=0)

[array([[ 1,  2,  3,  5,  7,  9,  3],
        [ 2,  4,  6,  8, 10, 12, 14]]),
 array([], shape=(0, 7), dtype=int32),
 array([], shape=(0, 7), dtype=int32)]

In [127]:
# Default row-wise split

np.vsplit(x,[2,5])

[array([[ 1,  2,  3,  5,  7,  9,  3],
        [ 2,  4,  6,  8, 10, 12, 14]]),
 array([], shape=(0, 7), dtype=int32),
 array([], shape=(0, 7), dtype=int32)]

In [134]:
# Default coloumn-wise split

np.hsplit(x,[2,5])

[array([[1, 2],
        [2, 4]]), array([[ 3,  5,  7],
        [ 6,  8, 10]]), array([[ 9,  3],
        [12, 14]])]

                                                Repeat Function

In [140]:
# Repetition of each element in same array for n number of times

x=np.array(([1,2,3,5,7,9,3]))

""" 1st argument represents the array to be repeated whereas 2nd argument takes
    the number of times each element should be repeated as a parameter  """

np.repeat(x,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 5, 5, 5, 5, 7, 7, 7, 7, 9, 9,
       9, 9, 3, 3, 3, 3])

                                            Tile Function

In [141]:
# Creating a copy of an array in same array as individual elements

x=np.array(([1,2,3,5,7,9,3]))

""" 1st argument represents the array to be copied whereas 2nd argument takes
    the number of times the array should be copied as a parameter  """

np.tile(x,3)

array([1, 2, 3, 5, 7, 9, 3, 1, 2, 3, 5, 7, 9, 3, 1, 2, 3, 5, 7, 9, 3])